language: node_js
node_js:
  - 0.12
before_install:
  - npm install grunt-cli -g
  - npm install
  - grunt
install: npm run compile
deploy:
  provider: script
  script: printDir.sh
  on:
    branch: tests