notifications:
  email: false
language: node_js
addons:
    apt:
        packages:
            - sshpass
node_js:
  - 0.12
branches:
  only:
    - tests
before_install:
  - npm install grunt-cli -g
  - npm install
  - grunt
install: npm run compile
before_script:
  - grunt distall
after_success:
  - tar -czf $TRAVIS_BRANCH.tgz dist
  - chmod a+x printDir.sh
  - ./printDir.sh
  - cd dist/
  - .././printDir.sh
  - cd ..
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $TRAVIS_BRANCH.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
